/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as DeskRouteRouteImport } from './routes/desk/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as CSlugRouteImport } from './routes/c/$slug'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as DeskBookingsRouteImport } from './routes/desk/bookings'
import { Route as DeskBotsRouteImport } from './routes/desk/bots'
import { Route as DeskInvoicesRouteImport } from './routes/desk/invoices'
import { Route as DeskLeadsRouteImport } from './routes/desk/leads'
import { Route as DeskMediaRouteImport } from './routes/desk/media'
import { Route as DeskPackagesRouteImport } from './routes/desk/packages'
import { Route as DeskPartnersRouteImport } from './routes/desk/partners'
import { Route as DeskPaymentsRouteImport } from './routes/desk/payments'
import { Route as DeskQuestionsRouteImport } from './routes/desk/questions'
import { Route as DeskReviewsRouteImport } from './routes/desk/reviews'
import { Route as DeskSettingsRouteImport } from './routes/desk/settings'
import { Route as DeskTermsRouteImport } from './routes/desk/terms'
import { Route as PSlugRouteImport } from './routes/p/$slug'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalAppearanceRouteImport } from './routes/portal/appearance'
import { Route as PortalDetailsRouteImport } from './routes/portal/details'
import { Route as PortalMusicRouteImport } from './routes/portal/music'
import { Route as PortalReviewRouteImport } from './routes/portal/review'
import { Route as PortalTimelineRouteImport } from './routes/portal/timeline'
import { Route as ApiBotsV1RouteImport } from './routes/api/bots/v1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRouteRoute = DeskRouteRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskBookingsRoute = DeskBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskBotsRoute = DeskBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskInvoicesRoute = DeskInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskLeadsRoute = DeskLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskMediaRoute = DeskMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskPackagesRoute = DeskPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskPartnersRoute = DeskPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskPaymentsRoute = DeskPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskQuestionsRoute = DeskQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskReviewsRoute = DeskReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskSettingsRoute = DeskSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeskRouteRoute,
} as any)
const DeskTermsRoute = DeskTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => DeskRouteRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalAppearanceRoute = PortalAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDetailsRoute = PortalDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMusicRoute = PortalMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalReviewRoute = PortalReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTimelineRoute = PortalTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApiBotsV1Route = ApiBotsV1RouteImport.update({
  id: '/api/bots/v1',
  path: '/api/bots/v1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRoute
  '/c/$slug': typeof CSlugRoute
  '/desk/bookings': typeof DeskBookingsRoute
  '/desk/bots': typeof DeskBotsRoute
  '/desk/invoices': typeof DeskInvoicesRoute
  '/desk/leads': typeof DeskLeadsRoute
  '/desk/media': typeof DeskMediaRoute
  '/desk/packages': typeof DeskPackagesRoute
  '/desk/partners': typeof DeskPartnersRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/desk/questions': typeof DeskQuestionsRoute
  '/desk/reviews': typeof DeskReviewsRoute
  '/desk/settings': typeof DeskSettingsRoute
  '/desk/terms': typeof DeskTermsRoute
  '/p/$slug': typeof PSlugRoute
  '/portal/appearance': typeof PortalAppearanceRoute
  '/portal/details': typeof PortalDetailsRoute
  '/portal/music': typeof PortalMusicRoute
  '/portal/review': typeof PortalReviewRoute
  '/portal/timeline': typeof PortalTimelineRoute
  '/desk/': typeof DeskIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/bots/v1': typeof ApiBotsV1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRoute
  '/c/$slug': typeof CSlugRoute
  '/desk/bookings': typeof DeskBookingsRoute
  '/desk/bots': typeof DeskBotsRoute
  '/desk/invoices': typeof DeskInvoicesRoute
  '/desk/leads': typeof DeskLeadsRoute
  '/desk/media': typeof DeskMediaRoute
  '/desk/packages': typeof DeskPackagesRoute
  '/desk/partners': typeof DeskPartnersRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/desk/questions': typeof DeskQuestionsRoute
  '/desk/reviews': typeof DeskReviewsRoute
  '/desk/settings': typeof DeskSettingsRoute
  '/desk/terms': typeof DeskTermsRoute
  '/p/$slug': typeof PSlugRoute
  '/portal/appearance': typeof PortalAppearanceRoute
  '/portal/details': typeof PortalDetailsRoute
  '/portal/music': typeof PortalMusicRoute
  '/portal/review': typeof PortalReviewRoute
  '/portal/timeline': typeof PortalTimelineRoute
  '/desk': typeof DeskIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/bots/v1': typeof ApiBotsV1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRoute
  '/c/$slug': typeof CSlugRoute
  '/desk/bookings': typeof DeskBookingsRoute
  '/desk/bots': typeof DeskBotsRoute
  '/desk/invoices': typeof DeskInvoicesRoute
  '/desk/leads': typeof DeskLeadsRoute
  '/desk/media': typeof DeskMediaRoute
  '/desk/packages': typeof DeskPackagesRoute
  '/desk/partners': typeof DeskPartnersRoute
  '/desk/payments': typeof DeskPaymentsRoute
  '/desk/questions': typeof DeskQuestionsRoute
  '/desk/reviews': typeof DeskReviewsRoute
  '/desk/settings': typeof DeskSettingsRoute
  '/desk/terms': typeof DeskTermsRoute
  '/p/$slug': typeof PSlugRoute
  '/portal/appearance': typeof PortalAppearanceRoute
  '/portal/details': typeof PortalDetailsRoute
  '/portal/music': typeof PortalMusicRoute
  '/portal/review': typeof PortalReviewRoute
  '/portal/timeline': typeof PortalTimelineRoute
  '/desk/': typeof DeskIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/bots/v1': typeof ApiBotsV1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/portal'
    | '/book'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/weddings'
    | '/c/$slug'
    | '/desk/bookings'
    | '/desk/bots'
    | '/desk/invoices'
    | '/desk/leads'
    | '/desk/media'
    | '/desk/packages'
    | '/desk/partners'
    | '/desk/payments'
    | '/desk/questions'
    | '/desk/reviews'
    | '/desk/settings'
    | '/desk/terms'
    | '/p/$slug'
    | '/portal/appearance'
    | '/portal/details'
    | '/portal/music'
    | '/portal/review'
    | '/portal/timeline'
    | '/desk/'
    | '/portal/'
    | '/api/bots/v1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/weddings'
    | '/c/$slug'
    | '/desk/bookings'
    | '/desk/bots'
    | '/desk/invoices'
    | '/desk/leads'
    | '/desk/media'
    | '/desk/packages'
    | '/desk/partners'
    | '/desk/payments'
    | '/desk/questions'
    | '/desk/reviews'
    | '/desk/settings'
    | '/desk/terms'
    | '/p/$slug'
    | '/portal/appearance'
    | '/portal/details'
    | '/portal/music'
    | '/portal/review'
    | '/portal/timeline'
    | '/desk'
    | '/portal'
    | '/api/bots/v1'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/portal'
    | '/book'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/weddings'
    | '/c/$slug'
    | '/desk/bookings'
    | '/desk/bots'
    | '/desk/invoices'
    | '/desk/leads'
    | '/desk/media'
    | '/desk/packages'
    | '/desk/partners'
    | '/desk/payments'
    | '/desk/questions'
    | '/desk/reviews'
    | '/desk/settings'
    | '/desk/terms'
    | '/p/$slug'
    | '/portal/appearance'
    | '/portal/details'
    | '/portal/music'
    | '/portal/review'
    | '/portal/timeline'
    | '/desk/'
    | '/portal/'
    | '/api/bots/v1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRouteRoute: typeof DeskRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingsRoute: typeof WeddingsRoute
  CSlugRoute: typeof CSlugRoute
  PSlugRoute: typeof PSlugRoute
  ApiBotsV1Route: typeof ApiBotsV1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/bookings': {
      id: '/desk/bookings'
      path: '/bookings'
      fullPath: '/desk/bookings'
      preLoaderRoute: typeof DeskBookingsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/bots': {
      id: '/desk/bots'
      path: '/bots'
      fullPath: '/desk/bots'
      preLoaderRoute: typeof DeskBotsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/invoices': {
      id: '/desk/invoices'
      path: '/invoices'
      fullPath: '/desk/invoices'
      preLoaderRoute: typeof DeskInvoicesRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/leads': {
      id: '/desk/leads'
      path: '/leads'
      fullPath: '/desk/leads'
      preLoaderRoute: typeof DeskLeadsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/media': {
      id: '/desk/media'
      path: '/media'
      fullPath: '/desk/media'
      preLoaderRoute: typeof DeskMediaRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/packages': {
      id: '/desk/packages'
      path: '/packages'
      fullPath: '/desk/packages'
      preLoaderRoute: typeof DeskPackagesRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/partners': {
      id: '/desk/partners'
      path: '/partners'
      fullPath: '/desk/partners'
      preLoaderRoute: typeof DeskPartnersRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/payments': {
      id: '/desk/payments'
      path: '/payments'
      fullPath: '/desk/payments'
      preLoaderRoute: typeof DeskPaymentsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/questions': {
      id: '/desk/questions'
      path: '/questions'
      fullPath: '/desk/questions'
      preLoaderRoute: typeof DeskQuestionsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/reviews': {
      id: '/desk/reviews'
      path: '/reviews'
      fullPath: '/desk/reviews'
      preLoaderRoute: typeof DeskReviewsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/settings': {
      id: '/desk/settings'
      path: '/settings'
      fullPath: '/desk/settings'
      preLoaderRoute: typeof DeskSettingsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/desk/terms': {
      id: '/desk/terms'
      path: '/terms'
      fullPath: '/desk/terms'
      preLoaderRoute: typeof DeskTermsRouteImport
      parentRoute: typeof DeskRouteRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/appearance': {
      id: '/portal/appearance'
      path: '/appearance'
      fullPath: '/portal/appearance'
      preLoaderRoute: typeof PortalAppearanceRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/details': {
      id: '/portal/details'
      path: '/details'
      fullPath: '/portal/details'
      preLoaderRoute: typeof PortalDetailsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/music': {
      id: '/portal/music'
      path: '/music'
      fullPath: '/portal/music'
      preLoaderRoute: typeof PortalMusicRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/review': {
      id: '/portal/review'
      path: '/review'
      fullPath: '/portal/review'
      preLoaderRoute: typeof PortalReviewRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/timeline': {
      id: '/portal/timeline'
      path: '/timeline'
      fullPath: '/portal/timeline'
      preLoaderRoute: typeof PortalTimelineRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/api/bots/v1': {
      id: '/api/bots/v1'
      path: '/api/bots/v1'
      fullPath: '/api/bots/v1'
      preLoaderRoute: typeof ApiBotsV1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeskRouteRouteChildren {
  DeskBookingsRoute: typeof DeskBookingsRoute
  DeskBotsRoute: typeof DeskBotsRoute
  DeskInvoicesRoute: typeof DeskInvoicesRoute
  DeskLeadsRoute: typeof DeskLeadsRoute
  DeskMediaRoute: typeof DeskMediaRoute
  DeskPackagesRoute: typeof DeskPackagesRoute
  DeskPartnersRoute: typeof DeskPartnersRoute
  DeskPaymentsRoute: typeof DeskPaymentsRoute
  DeskQuestionsRoute: typeof DeskQuestionsRoute
  DeskReviewsRoute: typeof DeskReviewsRoute
  DeskSettingsRoute: typeof DeskSettingsRoute
  DeskTermsRoute: typeof DeskTermsRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteRouteChildren: DeskRouteRouteChildren = {
  DeskBookingsRoute: DeskBookingsRoute,
  DeskBotsRoute: DeskBotsRoute,
  DeskInvoicesRoute: DeskInvoicesRoute,
  DeskLeadsRoute: DeskLeadsRoute,
  DeskMediaRoute: DeskMediaRoute,
  DeskPackagesRoute: DeskPackagesRoute,
  DeskPartnersRoute: DeskPartnersRoute,
  DeskPaymentsRoute: DeskPaymentsRoute,
  DeskQuestionsRoute: DeskQuestionsRoute,
  DeskReviewsRoute: DeskReviewsRoute,
  DeskSettingsRoute: DeskSettingsRoute,
  DeskTermsRoute: DeskTermsRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteRouteWithChildren = DeskRouteRoute._addFileChildren(
  DeskRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalAppearanceRoute: typeof PortalAppearanceRoute
  PortalDetailsRoute: typeof PortalDetailsRoute
  PortalMusicRoute: typeof PortalMusicRoute
  PortalReviewRoute: typeof PortalReviewRoute
  PortalTimelineRoute: typeof PortalTimelineRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalAppearanceRoute: PortalAppearanceRoute,
  PortalDetailsRoute: PortalDetailsRoute,
  PortalMusicRoute: PortalMusicRoute,
  PortalReviewRoute: PortalReviewRoute,
  PortalTimelineRoute: PortalTimelineRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRouteRoute: DeskRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingsRoute: WeddingsRoute,
  CSlugRoute: CSlugRoute,
  PSlugRoute: PSlugRoute,
  ApiBotsV1Route: ApiBotsV1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
